### ISSUE TITLE
Binding of application with the  CF-AutoScaler  service failing

### ISSUE THREAD

**Issue by ghaih** [cfibmers/open-Autoscaler#1]
Hi ,

I have set up the service as mentioned (in bosh-lite environment). All apps show the as started. When  invoke cf bind-service, it fails as follows,

FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: CWSCV2003E: The Auto-Scaling service broker failed to bind the service instance {0}.

Could you please help resolving this issue.

Regards
Harpreet

**Comment by cdlliuy** [comment]
@ghaih,  could you help to provide the logs of AutoScalingServiceBroker when the error happens ? cf logs AutoScalingServiceBroker --recent will help to collect the information. 

The most possible reason is the incorrect connection to database.  If possible, please paste the your profile file <project>/profiles/<profile>.properties here as well. Thanks.

**Comment by boyang9527** [comment]
One important thing you may take care of is the couchdb setting, as Ying said above. The settings in the sample is a test account, and if someone already used it and did not clear the data, there will be problem.  You may either login and delete the databases, or create another account on cloudant.com, or have a couchdb installed by yourself. 

couchdbUsername=autoscaler
couchdbPassword=openopen
couchdbHost=autoscaler.cloudant.com
couchdbPort=80

We will remove couchdb setting in the sample to avoid confusion.  
There is plan to add support of other type of databases, to allow choices for data persistency.

**Comment by ghaih** [comment]
Hi, 

### Following is the the configuration

> > > display AutoScaler server configuration:  :
> > > cfUrl=api.10.244.0.34.xip.io
> > > cfClientId=cf-autoscaler-client
> > > cfClientSecret=cf-autoscaler-client-secret
> > > couchdbHost=localhost
> > > couchdbPort=5984
> > > couchdbUsername=autoscaler
> > > couchdbPassword=openopen
> > > internalAuthUsername=admin
> > > internalAuthPassword=admin
> > > 
> > > display AutoScaler api configuration:  :
> > > cfUrl=api.10.244.0.34.xip.io
> > > cfClientId=cf-autoscaler-client
> > > cfClientSecret=cf-autoscaler-client-secret
> > > internalAuthUsername=admin
> > > internalAuthPassword=admin
> > > 
> > > display AutoScaler servicebroker configuration:  :
> > > couchdbHost=localhost
> > > couchdbPort=5984
> > > couchdbUsername=autoscaler
> > > couchdbPassword=openopen
> > > brokerUsername=admin
> > > brokerPassword=admin
> > > internalAuthUsername=admin
> > > internalAuthPassword=admin
> > > serverURIList=AutoScaling.10.244.0.34.xip.io
> > > apiServerURI=AutoScalingAPI.10.244.0.34.xip.io

### Application status

name                       requested state   instances   memory   disk   urls
ScalingTestApp       stopped               0/1             256M     1G     scalingtestapp-unstrangulable-precurriculum.10.244.0.34.xip.io
AutoScaling             started                1/1             256M     1G     autoscaling.10.244.0.34.xip.io
AutoScalingAPI       started                1/1             256M     1G     autoscalingapi.10.244.0.34.xip.io
dora                          started               1/1             256M     1G     dora.10.244.0.34.xip.io
AutoScalingServiceBroker   started   1/1             256M     1G     autoscalingservicebroker.10.244.0.34.xip.io

### Application binding

I try binding application dora to service ScalerServiceTest

### cf logs AutoScalingServiceBroker

(Includes service creation and application binding log)
Connected, tailing logs for app AutoScalingServiceBroker in org me / space development as admin...

2016-03-11T09:33:53.62+1100 [App/0]      OUT 2016-03-10 22:33:53,621 INFO  org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:54 [http-nio-61017-exec-2] [provisionService] input request:{"service_id":"CF-AutoScaler-id","plan_id":"CF-AutoScaler-free-plan","organization_guid":"76c16fd4-09d2-4549-9db3-c39457855441","space_guid":"7ff071c2-353c-442e-8c69-c412c399e3be"}
2016-03-11T09:33:53.62+1100 [App/0]      OUT 2016-03-10 22:33:53,621 INFO  org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:65 [http-nio-61017-exec-2] [provisionService] Entry: Provisioning service for serviceId 6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4 , orgId 76c16fd4-09d2-4549-9db3-c39457855441, spaceId 7ff071c2-353c-442e-8c69-c412c399e3be
2016-03-11T09:33:55.11+1100 [App/0]      OUT 2016-03-10 22:33:55,110 INFO  org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:72 [http-nio-61017-exec-2] [provisionService] Success: Provisioning service for serviceId 6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4 , orgId 76c16fd4-09d2-4549-9db3-c39457855441, spaceId 7ff071c2-353c-442e-8c69-c412c399e3be  with response {"dashboard_url":"https://AutoScaling.bosh-lite.com"}
2016-03-11T09:33:55.11+1100 [RTR/0]      OUT AutoScalingServiceBroker.10.244.0.34.xip.io - [10/03/2016:22:33:53 +0000] "PUT /v2/service_instances/6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4?accepts_incomplete=true HTTP/1.1" 201 180 53 "-" "HTTPClient/1.0 (2.5.3.3, ruby 2.1.6 (2015-04-13))" 10.0.2.15:53220 x_forwarded_for:"10.0.2.15, 10.0.2.15" vcap_request_id:9287974e-d62f-4854-495b-1906044dff89 response_time:1.500250272 app_id:d1a31a31-79d1-4cb4-93c7-d058ebdb5039
2016-03-11T09:34:27.10+1100 [App/0]      OUT 2016-03-10 22:34:27,106 INFO  org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:91 [http-nio-61017-exec-4] [bindService] input request:{"service_id":"CF-AutoScaler-id","plan_id":"CF-AutoScaler-free-plan","app_guid":"06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c"}
2016-03-11T09:34:27.10+1100 [App/0]      OUT 2016-03-10 22:34:27,107 INFO  org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:100 [http-nio-61017-exec-4] [bindService] Entry: Bind service for serviceId 6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4 , bindingId 815879f8-c752-4b96-a1ba-b0110c869588, appId 06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c
2016-03-11T09:34:27.94+1100 [App/0]      OUT 2016-03-10 22:34:27,940 INFO  org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr:196 [http-nio-61017-exec-4] [registerAppWithServer] registerUrl is  https://AutoScaling.bosh-lite.com/resources/brokercallback with appId 06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c
2016-03-11T09:34:27.94+1100 [App/0]      OUT 2016-03-10 22:34:27,941 INFO  org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr:197 [http-nio-61017-exec-4] [registerAppWithServer] registerJSON is  {"spaceId":"7ff071c2-353c-442e-8c69-c412c399e3be","agentUsername":"agent","appId":"06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c","bindingId":"815879f8-c752-4b96-a1ba-b0110c869588","serviceId":"6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4","agentPassword":"aa1d1205-e486-4ba4-a76e-dc9f3dd7c6c8","orgId":"76c16fd4-09d2-4549-9db3-c39457855441"}
2016-03-11T09:34:27.95+1100 [App/0]      OUT 2016-03-10 22:34:27,954 INFO  org.cloudfoundry.autoscaler.servicebroker.restclient.RestClientJersey$ConnectionFactory:192 [http-nio-61017-exec-4] [getHttpURLConnection] setup SSL contxt here
2016-03-11T09:34:28.35+1100 [App/0]      OUT 2016-03-10 22:34:28,354 ERROR org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr:218 [http-nio-61017-exec-4] [registerAppWithServer] bind failed for service  6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4 appId 06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c with error returned from service side with code 404, reason 404 Not Found: Requested route ('AutoScaling.bosh-lite.com') does not exist.
2016-03-11T09:34:28.35+1100 [App/0]      OUT 2016-03-10 22:34:28,354 ERROR org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest:117 [http-nio-61017-exec-4] [bindService] Failed: Bind service for serviceId 6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4 , bindingId 815879f8-c752-4b96-a1ba-b0110c869588, appId 06a40536-7f2f-48d2-8dc7-f0a25d0a8b6c  with execption 404 Not Found: Requested route ('AutoScaling.bosh-lite.com') does not exist.
2016-03-11T09:34:28.35+1100 [App/0]      OUT org.cloudfoundry.autoscaler.servicebroker.exception.ScalingServerFailureException: 404 Not Found: Requested route ('AutoScaling.bosh-lite.com') does not exist.
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr.registerAppWithServer(ScalingServiceMgr.java:227)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr.bindService(ScalingServiceMgr.java:62)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest.bindService(AutoScalingServiceBrokerRest.java:103)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at java.lang.reflect.Method.invoke(Method.java:497)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.filter.BrokerTokenAuthFilter.doFilter(BrokerTokenAuthFilter.java:66)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2016-03-11T09:34:28.35+1100 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745)
2016-03-11T09:34:28.37+1100 [RTR/0]      OUT AutoScalingServiceBroker.10.244.0.34.xip.io - [10/03/2016:22:34:27 +0000] "PUT /v2/service_instances/6f72dcc3-b9e4-46e2-94cf-519cc1dff9f4/service_bindings/815879f8-c752-4b96-a1ba-b0110c869588 HTTP/1.1" 499 119 104 "-" "HTTPClient/1.0 (2.5.3.3, ruby 2.1.6 (2015-04-13))" 10.0.2.15:53393 x_forwarded_for:"10.0.2.15, 10.0.2.15" vcap_request_id:d92e8afb-6c88-4f29-72b4-29172b2eb781 response_time:1.282917226 app_id:d1a31a31-79d1-4cb4-93c7-d058ebdb5039
2016-03-11T09:34:28.38+1100 [App/0]      OUT 2016-03-10 22:34:28,357 ERROR org.cloudfoundry.autoscaler.servicebroker.util.RestApiResponseUtil:87 [http-nio-61017-exec-4] [getResponseError] CWSCV2003E: The Auto-Scaling service broker failed to bind the service instance {0}.
2016-03-11T09:34:28.38+1100 [App/0]      OUT org.cloudfoundry.autoscaler.servicebroker.exception.ScalingServerFailureException: 404 Not Found: Requested route ('AutoScaling.bosh-lite.com') does not exist.
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr.registerAppWithServer(ScalingServiceMgr.java:227)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.mgr.ScalingServiceMgr.bindService(ScalingServiceMgr.java:62)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.rest.AutoScalingServiceBrokerRest.bindService(AutoScalingServiceBrokerRest.java:103)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at java.lang.reflect.Method.invoke(Method.java:497)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.cloudfoundry.autoscaler.servicebroker.filter.BrokerTokenAuthFilter.doFilter(BrokerTokenAuthFilter.java:66)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2016-03-11T09:34:28.38+1100 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745)

### Note:

I can see the service instance url is https://AutoScaling.bosh-lite.com, which in my opinion should be Autoscaling.10.244.0.34.xip.io

Thanks
Harpreet

**Comment by cdlliuy** [comment]
@ghaih , if your profile is not named as <sample>, did you enable it in your ~/.m2/setting.xml? 

> > > Define customized Maven profile name: (default: test): test
> > > Please paste the following into ~/.m2/settings.xml <profiles> section
> > >     <profile>
> > >             <id>test</id>
> > >             <properties>
> > >                 <build.profile.id>test</build.profile.id>
> > >             </properties>
> > >         </profile>
> > > If the above action is not done, the sample profile is enabled by default,  in which AutoScaling.bosh-lite.com is defined. 

You can check the finalized configuration file of service broker from:
/servicebroker/target/servicebroker-1.0-SNAPSHOT/WEB-INF/classes/config.properties

By the way, did you create couch db locally with below setting?
couchdbUsername=autoscaler
couchdbPassword=openopen
couchdbHost=localhost
couchdbPort=5984

If no, then your couch configuration is invalid

**Comment by ghaih** [comment]
Yes I created couch db locally.Initially i had been doing the packaging and rest of the steps in one go using ./getStart.sh. But the i checked the config properties were not having the couchdb info as localhost and 5984 but they were autoscaler.cloudant.com and 80 which is not the ones that i specified when prompted while running the getStart script.

Also i didnot change the profile name.

**Comment by ghaih** [comment]
I installed couchdb locally following the instructions at https://www.digitalocean.com/community/tutorials/how-to-install-couchdb-and-futon-on-ubuntu-14-04.
Also do i need to create a database.

Now I'm getting
Running org.cloudfoundry.autoscaler.servicebroker.data.entity.dao.couchdb.couchdbDAOTest
2016-03-11 15:20:04,793 ERROR org.cloudfoundry.autoscaler.servicebroker.data.storeservice.couchdb.CouchdbStoreService:45 [main] [<init>] 401:Unauthorized
URI: /couchdb-scalingbroker/
Response Body:
{
  "error" : "unauthorized",
  "reason" : "Name or password is incorrect."
}
org.ektorp.DbAccessException: 401:Unauthorized
URI: /couchdb-scalingbroker/
Response Body:
{
  "error" : "unauthorized",
  "reason" : "Name or password is incorrect."
}
 at org.ektorp.http.StdResponseHandler.createDbAccessException(StdResponseHandler.java:50)
        at org.ektorp.http.StdResponseHandler.error(StdResponseHandler.java:68)
        at org.ektorp.http.RestTemplate.handleVoidResponse(RestTemplate.java:113)
        at org.ektorp.http.RestTemplate.put(RestTemplate.java:39)
        at org.ektorp.impl.StdCouchDbInstance.createDatabase(StdCouchDbInstance.java:57)
        at org.ektorp.impl.StdCouchDbInstance.createDatabase(StdCouchDbInstance.java:49)
        at org.cloudfoundry.autoscaler.servicebroker.data.storeservice.couchdb.CouchdbStoreService.initConnection(CouchdbStoreService.java:211)
        at org.cloudfoundry.autoscaler.servicebroker.data.storeservice.couchdb.CouchdbStoreService.<init>(CouchdbStoreService.java:40)
        at org.cloudfoundry.autoscaler.servicebroker.data.storeservice.couchdb.CouchdbStoreService.<clinit>(CouchdbStoreService.java:29)
        at org.cloudfoundry.autoscaler.servicebroker.data.entity.dao.couchdb.couchdbDAOTest.initConnection(couchdbDAOTest.java:151)
        at org.cloudfoundry.autoscaler.servicebroker.data.entity.dao.couchdb.couchdbDAOTest.setUpBeforeClass(couchdbDAOTest.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by boyang9527** [comment]
Looks like you did not pass the UT of couchdb test in service broker.  If your profile has the following setting, you may need to leave the username and password blank, or pls configure your local couch db to add the user.

couchdbUsername=autoscaler
couchdbPassword=openopen
couchdbHost=localhost
couchdbPort=5984

By the way, once you push your service broker to bosh-lite, the setting of couch db above will not work since the localhost is the host of your app container, not your desktop. you will need a couch db that can be accessed from your app container.

**Comment by ghaih** [comment]
Thanks boyang, 
It worked when I fixed the couchdb setting in default.ini from bind_address = 127.0.0.1 to bind_address = 0.0.0.0
